ganesha-nfs:
  image: oscargil/rancher-ganesha-nfs:4.6
  # 4.6 = OK
# 4.3 # la del Jan en mi repo - 4.4 - base de 4.3 // 4.5 compilada de 0 no va
#  image: janeczku/rancher-ganesha-nfs:dev8
  command: /opt/rancher/start_nfs.sh
  privileged: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
#    io.rancher.scheduler.affinity:host_label: host=${HOSTID}
  volumes:
    - ${HOST_MOUNT}${EXPORT_BASE_PATH}
