.catalog:
  name: "Wordpress"
  version: "v0.1-educaas1"
  description: "Blog tool, publishing platform and CMS"
  uuid: Wordpress-0
  minimum_rancher_version: v0.51.0
  questions:    
    - variable: PUBLIC_PORT
      description: "public port to access the wordpress site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: DB_CLOUD_SELECTOR
      label: "DB Cloud Selector"
      description: "Define the Cloud where the DB will be deployed"
      required: true
      default: "OTC"
      type: "enum"
        - none
        - OTC
        - vCloud
    - variable: WORDPRESS_CLOUD_SELECTOR
      label: "Wordpress Cloud Selector"
      description: "Define the Cloud where the Application will be deployed"
      required: true
      default: "vCloud"
      type: "enum"
        - none
        - OTC
        - vCloud
