backup:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.scheduler.global: 'true'
  privileged: true
  pid: host
  volumes:
    - /lib/modules:/lib/modules:ro
    - /proc:/host/proc
    - /var/run:/host/var/run
    - /run:/host/run
    - /etc/docker/plugins:/etc/docker/plugins
  image: ubuntu:14.04.3
