.catalog:
    name: "persistent-storage-backup"
    version: "v0.0.1"
    description: "Automatic Persistent Storage Backup"
    questions:
     - variable: "DATA_VOL"
       description: "Origin Data Volume from Ganesha-nfs. If you have not change the defaults at the time of deploying Ganesha-nfs, leave the default"
       label: "DATA VOLUME"
       required: true
       type: "string"
       default: "nfs_data"
     - variable: "BACKUP_VOL"
       description: "Origin Backup Volume form Ganesha-nfs. If you have not change the defaults at the time of deploying Ganesha-nfs, leave the default"
       label: "BACKUP VOLUME"
       required: yes
       type: "string"
       default: "backup"
     - variable: "TIME_BACKUP"
       decription: "Number of minutes between backups"
       label: "Backup Time in minutes"
       required: yes
       type: "int"
       default: "60"
