.catalog:
    name: "backup-tools"
    version: "v0.0.1"
    description: "Backup Tools"
    questions:
     - variable: "DATA_VOL"
       description: "Origin Data Volume"
       label: "DATA VOLUME"
       required: true
       type: "string"

backup-tools:
    metadata:
        data_vol: "${"DATA_VOL}"
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10245     
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
